name: flutter_script_renderer
description: A Flutter package for automatic rendering of multilingual text with proper script-specific styling, supporting Khmer and Latin scripts with extensibility for additional languages.
version: 0.1.1
repository: https://github.com/sovanken/flutter-script-renderer
homepage: https://github.com/sovanken/flutter-script-renderer
issue_tracker: https://github.com/sovanken/flutter-script-renderer/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
      - lib/assets/fonts/
  fonts:
    # Khmer Fonts
    - family: Battambang
      fonts:
        - asset: lib/assets/fonts/km/Battambang-Black.ttf
        - asset: lib/assets/fonts/km/Battambang-Bold.ttf
        - asset: lib/assets/fonts/km/Battambang-Light.ttf
        - asset: lib/assets/fonts/km/Battambang-Regular.ttf
        - asset: lib/assets/fonts/km/Battambang-Thin.ttf

    - family: Koulen
      fonts:
        - asset: lib/assets/fonts/km/Koulen-Regular.ttf

    - family: Moul
      fonts:
        - asset: lib/assets/fonts/km/Moul-Regular.ttf

    - family: NotoSerifKhmer
      fonts:
        - asset: lib/assets/fonts/km/NotoSerifKhmer-Black.ttf
        - asset: lib/assets/fonts/km/NotoSerifKhmer-Bold.ttf
        - asset: lib/assets/fonts/km/NotoSerifKhmer-ExtraBold.ttf
        - asset: lib/assets/fonts/km/NotoSerifKhmer-ExtraLight.ttf
        - asset: lib/assets/fonts/km/NotoSerifKhmer-Light.ttf
        - asset: lib/assets/fonts/km/NotoSerifKhmer-Medium.ttf
        - asset: lib/assets/fonts/km/NotoSerifKhmer-Regular.ttf
        - asset: lib/assets/fonts/km/NotoSerifKhmer-SemiBold.ttf
        - asset: lib/assets/fonts/km/NotoSerifKhmer-Thin.ttf

    - family: Siemreap
      fonts:
        - asset: lib/assets/fonts/km/Siemreap-Regular.ttf

    - family: Suwannaphum
      fonts:
        - asset: lib/assets/fonts/km/Suwannaphum-Black.ttf
        - asset: lib/assets/fonts/km/Suwannaphum-Bold.ttf
        - asset: lib/assets/fonts/km/Suwannaphum-Light.ttf
        - asset: lib/assets/fonts/km/Suwannaphum-Regular.ttf
        - asset: lib/assets/fonts/km/Suwannaphum-Thin.ttf

    # English Fonts
    - family: IBMPlexSans
      fonts:
        - asset: lib/assets/fonts/en/IBMPlexSans.ttf

    - family: Inter
      fonts:
        - asset: lib/assets/fonts/en/Inter.ttf

    - family: Lato
      fonts:
        - asset: lib/assets/fonts/en/Lato-Bold.ttf
        - asset: lib/assets/fonts/en/Lato-BoldItalic.ttf
        - asset: lib/assets/fonts/en/Lato-Light.ttf
        - asset: lib/assets/fonts/en/Lato-Regular.ttf
        - asset: lib/assets/fonts/en/Lato-Thin.ttf

    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/en/Montserrat.ttf

    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/en/Nunito.ttf

    - family: OpenSans
      fonts:
        - asset: lib/assets/fonts/en/OpenSans.ttf

    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/en/Poppins-Light.ttf
        - asset: lib/assets/fonts/en/Poppins-Medium.ttf
        - asset: lib/assets/fonts/en/Poppins-Regular.ttf
        - asset: lib/assets/fonts/en/Poppins-Thin.ttf

    - family: Raleway
      fonts:
        - asset: lib/assets/fonts/en/Raleway.ttf

    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/en/Roboto.ttf

    - family: SFNSDisplay
      fonts:
        - asset: lib/assets/fonts/en/SFNSDisplay-Light.otf
        - asset: lib/assets/fonts/en/SFNSDisplay-Medium.otf
        - asset: lib/assets/fonts/en/SFNSDisplay-Regular.otf
        - asset: lib/assets/fonts/en/SFNSDisplay-Semibold.otf
        - asset: lib/assets/fonts/en/SFNSDisplay-Thin.otf